// Direction contract: operational CMS, sharp and legible; every public field stays editable inside curated layout rules.
import { IconAdjustments,IconArrowDown,IconArrowUp,IconBriefcase,IconBuilding,IconCheck,IconChevronRight,IconDeviceDesktop,IconDeviceMobile,IconDeviceTablet,IconEye,IconFileText,IconLayoutDashboard,IconLogout,IconMenu2,IconPhoto,IconPlus,IconSend,IconSparkles,IconTrash,IconUsers,IconX } from "@tabler/icons-react";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { Fragment, useEffect, useRef, useState } from "react";
import { defaultSiteContent, publicSitePayloadSchema, type PublicSitePayload, type SectionSettings } from "@perakaria/content-schema";

type View="dashboard"|"sections"|"services"|"expertise"|"portfolio"|"clients"|"media"|"theme"|"review"|"users"|"preview";
const nav=[
 ["dashboard","Dashboard",IconLayoutDashboard],["sections","Home content",IconFileText],["services","Service list",IconSparkles],["expertise","About buttons",IconUsers],["portfolio","Service thumbnails",IconBriefcase],["clients","Client cards",IconBuilding],["media","Upload media",IconPhoto],["theme","Theme & Site",IconAdjustments],["review","Review",IconSend],["users","Team access",IconUsers],["preview","Preview website",IconEye],
] as const;
const apiBase=import.meta.env.VITE_CMS_API_URL||"";
const readLocalDraft=()=>{try{const raw=localStorage.getItem("perakaria-cms-draft");if(!raw)return structuredClone(defaultSiteContent);const parsed=publicSitePayloadSchema.safeParse(JSON.parse(raw));if(!parsed.success)return structuredClone(defaultSiteContent);const content=parsed.data;content.sections=content.sections.filter(section=>section.id!=="services"&&section.id!=="expertise");if(content.settings.location==="Indonesia")content.settings.location=defaultSiteContent.settings.location;content.clients=content.clients.filter(client=>client.name!=="Puteri Indonesia"&&client.name!=="Enjoy Jakarta");return content}catch{return structuredClone(defaultSiteContent)}};

function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Status({value}:{value:string}){return <span className={`status status-${value}`}>{value.replace("_"," ")}</span>}
function PageHeading({title,copy,children}:{title:string;copy:string;children?:React.ReactNode}){return <div className="page-heading"><div><p className="overline">PERAKARIA CMS</p><h1>{title}</h1><p>{copy}</p></div>{children}</div>}

function Login({onLogin,error}:{onLogin:(e:string,p:string,d?:boolean)=>void;error:string}){const[e,setE]=useState("");const[p,setP]=useState("");return <main className="login-page"><section className="login-brand"><p>PERAKARIA / CONTENT SYSTEM</p><h1>Kontrol satu studio surface dari satu tempat.</h1><span>Theme. Story. Work. Publish.</span></section><form className="login-form" onSubmit={x=>{x.preventDefault();onLogin(e,p)}}><div className="admin-wordmark">PERAKA<span>RIA</span></div><p className="overline">CMS ADMIN</p><h2>Masuk ke workspace</h2><p>Edit seluruh konten public website tanpa mengubah kode.</p><Field label="Email"><input type="email" value={e} onChange={x=>setE(x.target.value)} placeholder="admin@perakaria.studio" required/></Field><Field label="Password"><input type="password" value={p} onChange={x=>setP(x.target.value)} minLength={12} required/></Field>{error&&<div className="form-error">{error}</div>}<button className="primary-action" type="submit">Masuk <IconChevronRight/></button><button className="demo-action" type="button" onClick={()=>onLogin("","",true)}>Buka demo lokal</button><small>Demo menyimpan draft di browser dan tidak mem-publish ke production.</small></form></main>}

function Dashboard({go}:{go:(v:View)=>void}){return <><PageHeading title="Selamat datang kembali." copy="Seluruh struktur sudah tersedia dan siap diisi ketika detail perusahaan final datang."><button className="primary-action" onClick={()=>go("preview")}><IconEye/>Preview website</button></PageHeading><div className="stat-grid">{[["11","Content types","Semua editable"],["6","Homepage sections","Urutan terkurasi"],["0","Pending review","Queue bersih"],["ID","Active locale","Bahasa Indonesia"]].map(x=><article className="stat" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span><small>{x[2]}</small></article>)}</div><div className="dashboard-columns"><section className="panel"><div className="panel-title"><p className="overline">QUICK ACCESS</p><h2>Kelola surface</h2></div>{nav.slice(1,6).map(([v,l,I])=><button className="quick-row" key={v} onClick={()=>go(v)}><I/><span>{l}</span><small>Buka editor</small><IconChevronRight/></button>)}</section><section className="panel activity"><div className="panel-title"><p className="overline">SYSTEM</p><h2>Readiness</h2></div><ul>{["Shared schema aktif","Safe fallback aktif","Contrast gate aktif"].map(x=><li key={x}><IconCheck/><span><b>{x}</b><small>Siap untuk workflow draft, review, dan publish.</small></span></li>)}</ul></section></div></>}

function Sections({content,update}:{content:PublicSitePayload;update:(n:PublicSitePayload)=>void}){
  const hero=(key:string,value:unknown)=>{const next=structuredClone(content) as any;next.hero[key]=value;update(next)};
  const about=(key:string,value:unknown)=>{const next=structuredClone(content) as any;next.about[key]=value;update(next)};
  const contact=(key:string,value:unknown)=>{const next=structuredClone(content) as any;next.contact[key]=value;update(next)};
  return <><PageHeading title="Home content" copy="Edit hanya field yang benar-benar tampil di website-v2. Media image/video dipasang lewat Upload media."/><div className="editor-stack">
    <details className="editor-card" open><summary><span className="order">01</span><div><strong>Hero</strong><small>Home / first viewport</small></div><Status value="published"/></summary><div className="card-form two-columns"><Field label="Deskripsi hero"><textarea rows={5} value={content.hero.body} onChange={e=>hero("body",e.target.value)}/></Field><Field label="Alt text hero poster"><input value={content.hero.posterAlt} onChange={e=>hero("posterAlt",e.target.value)}/></Field><Field label="Focal point X / Y"><div className="inline-inputs"><input type="number" min="0" max="100" value={content.hero.mediaFocalPoint.x} onChange={e=>hero("mediaFocalPoint",{...content.hero.mediaFocalPoint,x:Number(e.target.value)})}/><input type="number" min="0" max="100" value={content.hero.mediaFocalPoint.y} onChange={e=>hero("mediaFocalPoint",{...content.hero.mediaFocalPoint,y:Number(e.target.value)})}/></div></Field><p className="editor-help">Hero poster dan showreel dikelola dari Upload media → Hero.</p></div></details>
    <details className="editor-card"><summary><span className="order">02</span><div><strong>About / Reel</strong><small>Narasi dan media utama</small></div><Status value="published"/></summary><div className="card-form two-columns"><Field label="Narasi"><textarea rows={7} value={content.about.body} onChange={e=>about("body",e.target.value)}/></Field><Field label="Jenis media"><select value={content.about.mediaType} onChange={e=>about("mediaType",e.target.value)}><option value="video">Video</option><option value="image">Image</option></select></Field><p className="editor-help">Reel poster dan video dikelola dari Upload media → About / Reel.</p></div></details>
    <details className="editor-card"><summary><span className="order">03</span><div><strong>Contact / Grid</strong><small>CTA dan lima slot visual</small></div><Status value="published"/></summary><div className="editor-stack"><div className="card-form two-columns"><Field label="Label WhatsApp"><input value={content.contact.whatsappLabel} onChange={e=>contact("whatsappLabel",e.target.value)}/></Field><Field label="Label email"><input value={content.contact.emailLabel} onChange={e=>contact("emailLabel",e.target.value)}/></Field></div>{content.contact.galleryImages.map((image,index)=><div className="card-form two-columns" key={index}><div className="skill-media-preview"><img src={image.imageUrl} alt={image.imageAlt}/><span>Grid {String(index+1).padStart(2,"0")}</span></div><Field label={"Nama grid "+String(index+1).padStart(2,"0")}><input value={image.title} onChange={e=>{const next=structuredClone(content);next.contact.galleryImages[index].title=e.target.value;update(next)}}/></Field><Field label="Alt text"><input value={image.imageAlt} onChange={e=>{const next=structuredClone(content);next.contact.galleryImages[index].imageAlt=e.target.value;update(next)}}/></Field></div>)}</div></details>
  </div></>
}

function Collection({kind,content,update}:{kind:"services"|"portfolio"|"clients";content:PublicSitePayload;update:(n:PublicSitePayload)=>void}){
  const items=content[kind] as any[];
  const title=kind==="services"?"Service list":kind==="portfolio"?"Service thumbnails":"Client cards";
  const copy=kind==="services"?"Teks yang muncul di kolom WHAT WE DO.":kind==="portfolio"?"Thumbnail yang tampil di grid WHAT WE DO. Pasang image lewat Upload media.":"Logo dan nama client yang tampil di carousel website-v2.";
  const patch=(i:number,k:string,v:unknown)=>{const n=structuredClone(content) as any;n[kind][i][k]=v;update(n)};
  const add=()=>{const n=structuredClone(content);if(kind==="services")n.services.push({id:crypto.randomUUID(),title:"Service baru",category:"creative",description:"Tulis deskripsi service.",details:[],order:n.services.length+1,isVisible:true});if(kind==="portfolio")n.portfolio.push({id:crypto.randomUUID(),title:"Thumbnail baru",client:"Nama client",year:new Date().getFullYear(),category:"Production",summary:"",coverImageUrl:"",coverImageAlt:"Deskripsikan thumbnail.",mediaType:"image",videoUrl:"",order:n.portfolio.length+1,featured:true,isVisible:true,isPlaceholder:true});if(kind==="clients")n.clients.push({id:crypto.randomUUID(),name:"Client baru",logoUrl:"",logoAlt:"Deskripsikan logo client.",websiteUrl:"",order:n.clients.length+1,isVisible:true,isPlaceholder:true});update(n)};
  return <><PageHeading title={title} copy={copy}><button className="primary-action" onClick={add}><IconPlus/>Tambah {kind==="portfolio"?"thumbnail":kind==="clients"?"client":"service"}</button></PageHeading><div className="editor-stack">{items.map((it,i)=><details className="editor-card" key={it.id} open={i===0}><summary><span className="order">{String(i+1).padStart(2,"0")}</span><div><strong>{it.title||it.name}</strong><small>{kind==="portfolio"?"Thumbnail "+String(i+1).padStart(2,"0"):it.category||(it.isPlaceholder?"Belum diisi":"Siap tampil")}</small></div><Status value={it.isVisible?"published":"archived"}/></summary><div className="card-form two-columns">
    <Field label={kind==="clients"?"Nama client":"Nama / judul"}><input value={it.title||it.name} onChange={e=>patch(i,kind==="clients"?"name":"title",e.target.value)}/></Field>
    {kind==="services"&&<><Field label="Kategori"><select value={it.category} onChange={e=>patch(i,"category",e.target.value)}><option value="creative">Creative</option><option value="technology">Technology</option></select></Field><Field label="Deskripsi"><textarea rows={4} value={it.description} onChange={e=>patch(i,"description",e.target.value)}/></Field><Field label="Daftar item"><input value={it.details.join(", ")} onChange={e=>patch(i,"details",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/><small>Pisahkan dengan koma. Item ini menjadi checklist di website.</small></Field></>}
    {kind==="portfolio"&&<><Field label="Client / project"><input value={it.client} onChange={e=>patch(i,"client",e.target.value)}/></Field><Field label="Kategori"><input value={it.category} onChange={e=>patch(i,"category",e.target.value)}/></Field><div className="collection-media-state"><img src={it.coverImageUrl||"/assets/portfolio/thumb-01.svg"} alt={it.coverImageAlt}/><span>{it.coverImageUrl?"Thumbnail sudah terpasang":"Belum ada thumbnail · pasang dari Upload media"}</span></div><Field label="Alt text thumbnail"><input value={it.coverImageAlt} onChange={e=>patch(i,"coverImageAlt",e.target.value)}/></Field><Field label="Tampil di grid"><select value={String(it.featured)} onChange={e=>patch(i,"featured",e.target.value==="true")}><option value="true">Ya</option><option value="false">Tidak</option></select></Field></>}
    {kind==="clients"&&<><div className="collection-media-state"><img src={it.logoUrl||"/assets/clients/jti.svg"} alt={it.logoAlt||it.name}/><span>{it.logoUrl?"Logo sudah terpasang":"Belum ada logo · pasang dari Upload media"}</span></div><Field label="Alt text logo"><input value={it.logoAlt} onChange={e=>patch(i,"logoAlt",e.target.value)}/></Field><Field label="Website URL (opsional)"><input value={it.websiteUrl} onChange={e=>patch(i,"websiteUrl",e.target.value)}/></Field></>}
    <Field label="Urutan tampil"><input type="number" min="1" value={it.order} onChange={e=>patch(i,"order",Number(e.target.value))}/></Field><Field label="Tampilkan di website"><select value={String(it.isVisible)} onChange={e=>patch(i,"isVisible",e.target.value==="true")}><option value="true">Ya</option><option value="false">Tidak</option></select></Field>
  </div></details>)}</div></>}
  
function ExpertiseEditor({content,update}:{content:PublicSitePayload;update:(n:PublicSitePayload)=>void}){
  const patch=(index:number,key:string,value:unknown)=>{const next=structuredClone(content) as any;next.skills[index][key]=value;update(next)};
  const add=()=>{const next=structuredClone(content);next.skills.push({id:"skill-"+crypto.randomUUID(),name:"Tombol baru",description:"",specialistName:"",specialistRole:"",photoUrl:"",photoAlt:"",order:next.skills.length+1,isVisible:true,isPlaceholder:true});update(next)};
  const remove=(index:number)=>{const next=structuredClone(content);next.skills.splice(index,1);next.skills.forEach((skill,order)=>skill.order=order+1);update(next)};
  return <><PageHeading title="About buttons" copy="Website-v2 hanya memakai nama tombol ini di section Reel. Atur label dan urutannya tanpa field yang tidak tampil di website."><button className="primary-action" onClick={add}><IconPlus/>Tambah tombol</button></PageHeading><section className="panel"><div className="panel-title"><p className="overline">ABOUT / REEL</p><h2>Label tombol yang tampil</h2></div><div className="card-form"><p className="editor-help">Setiap baris menjadi satu tombol di bawah narasi PERAKARIA. Gunakan urutan untuk mengatur posisi dari kiri ke kanan.</p></div></section><div className="editor-stack expertise-editor-stack">{content.skills.map((skill,index)=><details className="editor-card" key={skill.id} open={index===0}><summary><span className="order">{String(index+1).padStart(2,"0")}</span><div><strong>{skill.name}</strong><small>About button</small></div><Status value={skill.isVisible?"published":"archived"}/></summary><div className="card-form two-columns"><Field label="Label tombol"><input value={skill.name} onChange={event=>patch(index,"name",event.target.value)}/></Field><Field label="Urutan"><input type="number" min="1" value={skill.order} onChange={event=>patch(index,"order",Number(event.target.value))}/></Field><Field label="Tampilkan di website"><select value={String(skill.isVisible)} onChange={event=>patch(index,"isVisible",event.target.value==="true")}><option value="true">Ya</option><option value="false">Tidak</option></select></Field><button className="secondary-action danger-action remove-skill" type="button" onClick={()=>remove(index)}><IconTrash/>Hapus tombol</button></div></details>)}</div></>
}
function Theme({content,update}:{content:PublicSitePayload;update:(n:PublicSitePayload)=>void}){
  const theme=(k:string,v:unknown)=>{const n=structuredClone(content) as any;n.theme[k]=v;update(n)};
  const palette=(k:string,v:string)=>{const n=structuredClone(content) as any;n.theme.palette[k]=v;if(k==="backgroundPrimary")n.theme.background=v;if(k==="backgroundSecondary")n.theme.surface=v;if(k==="titlePrimary")n.theme.accent=v;if(k==="titleSecondary")n.theme.accentSecondary=v;if(k==="textPrimary"){n.theme.text=v;n.theme.muted=v}update(n)};
  const setting=(k:string,v:unknown)=>{const n=structuredClone(content) as any;n.settings[k]=v;update(n)};
  return <><PageHeading title="Theme & Site Settings" copy="Edit identitas, kontak, SEO, dan enam token warna utama Perakaria."/><div className="settings-grid"><section className="panel"><div className="panel-title"><p className="overline">BRAND</p><h2>Site settings</h2></div><div className="card-form">{[["brandName","Brand name"],["shortName","Short name"],["logoUrl","Logo brand / wordmark URL"],["faviconUrl","Favicon URL"],["whatsapp","WhatsApp"],["email","Email"],["location","Location"],["seoTitle","SEO title"],["ogImageUrl","OG image URL"],["canonicalUrl","Canonical URL"]].map(([k,l])=><Field label={l} key={k}><input value={(content.settings as any)[k]} onChange={e=>setting(k,e.target.value)}/></Field>)}<Field label="SEO description"><textarea rows={4} value={content.settings.seoDescription} onChange={e=>setting("seoDescription",e.target.value)}/></Field><Field label="Instagram URL"><input value={content.settings.instagramUrl} onChange={e=>setting("instagramUrl",e.target.value)}/></Field><Field label="LinkedIn URL"><input value={content.settings.linkedinUrl} onChange={e=>setting("linkedinUrl",e.target.value)}/></Field><Field label="Vimeo URL"><input value={content.settings.vimeoUrl} onChange={e=>setting("vimeoUrl",e.target.value)}/></Field><Field label="Navigation JSON" hint="Edit label dan anchor tiap menu."><textarea rows={7} value={JSON.stringify(content.settings.navigation,null,2)} onChange={e=>{try{setting("navigation",JSON.parse(e.target.value))}catch{}}}/></Field></div></section><section className="panel"><div className="panel-title"><p className="overline">PUBLIC THEME</p><h2>Perakaria palette</h2></div><div className="card-form"><Field label="Motion"><select value={String(content.theme.motionEnabled)} onChange={e=>theme("motionEnabled",e.target.value==="true")}><option value="true">Enabled</option><option value="false">Reduced</option></select></Field><Field label={`Default overlay ${Math.round(content.theme.overlayOpacity*100)}%`}><input type="range" min="0" max=".9" step=".01" value={content.theme.overlayOpacity} onChange={e=>theme("overlayOpacity",Number(e.target.value))}/></Field></div><div className="color-list">{[["backgroundPrimary","Background 1 — #06121C"],["backgroundSecondary","Background 2 — #101010"],["titlePrimary","Title 1 — #8C62EF"],["titleSecondary","Title 2 — #D9D9D9"],["textPrimary","Text 1 — #FFFFFF"],["textSecondary","Text 2 — #000000"]].map(([k,l])=><Field label={l} key={k}><div className="color-input"><input type="color" value={(content.theme.palette as any)[k]} onChange={e=>palette(k,e.target.value)}/><input value={(content.theme.palette as any)[k]} onChange={e=>palette(k,e.target.value)}/></div></Field>)}</div><div className="contrast-note"><IconCheck/>Kontras palette divalidasi API sebelum publish.</div></section></div></>}
function Media({content,update,role}:{content:PublicSitePayload;update:(n:PublicSitePayload)=>void;role:"superadmin"|"admin_writer"|"demo"}){
  type UploadItem={id?:string;name:string;alt:string;url:string;kind:"image"|"video";pending?:boolean};
  type UploadTarget={id:string;label:string;detail:string;kind:"image"|"video";currentUrl:string};
  const [items,setItems]=useState<UploadItem[]>([]);
  const [alt,setAlt]=useState(""),[message,setMessage]=useState(""),[target,setTarget]=useState("hero.posterImageUrl"),[applied,setApplied]=useState("");
  const targetGroups:{label:string;description:string;items:UploadTarget[]}[]=[
    {label:"Hero",description:"Media pembuka website",items:[
      {id:"hero.posterImageUrl",label:"Hero poster",detail:"Gambar fallback / poster video",kind:"image",currentUrl:content.hero.posterImageUrl},
      {id:"hero.videoUrl",label:"Hero showreel",detail:"Video background otomatis",kind:"video",currentUrl:content.hero.videoUrl},
    ]},
    {label:"About / Reel",description:"Media utama section Reel",items:[
      {id:"about.imageUrl",label:"Reel poster",detail:"Gambar utama section Reel",kind:"image",currentUrl:content.about.imageUrl},
      {id:"about.videoUrl",label:"Reel video",detail:"Video section Reel",kind:"video",currentUrl:content.about.videoUrl},
    ]},
    {label:"Services / Thumbnails",description:"Thumbnail yang tampil di grid WHAT WE DO",items:content.portfolio.slice().sort((a,b)=>a.order-b.order).map((item,index)=>({id:"portfolio:"+item.id,label:"Thumbnail "+String(index+1).padStart(2,"0")+" — "+item.title,detail:"Urutan "+item.order+" · "+(item.isVisible?"Tampil":"Disembunyikan"),kind:"image" as const,currentUrl:item.coverImageUrl}))},
    {label:"Clients",description:"Logo client yang tampil di carousel",items:content.clients.slice().sort((a,b)=>a.order-b.order).map((client,index)=>({id:"client:"+client.id,label:"Client "+String(index+1).padStart(2,"0")+" — "+client.name,detail:"Urutan "+client.order+" · "+(client.isVisible?"Tampil":"Disembunyikan"),kind:"image" as const,currentUrl:client.logoUrl}))},
    {label:"Contact / Grid",description:"Visual grid pada section Contact",items:content.contact.galleryImages.map((image,index)=>({id:"contact-gallery:"+index,label:"Grid "+String(index+1).padStart(2,"0")+" — "+(image.title||"Visual contact"),detail:"Slot visual contact",kind:"image" as const,currentUrl:image.imageUrl}))},
  ];
  const targets=targetGroups.flatMap(group=>group.items);
  const selected=targets.find(item=>item.id===target)||targets[0];
  useEffect(()=>{if(!apiBase||role==="demo")return;apiJson("/admin/media").then((data:any[])=>setItems((data||[]).map((m:any)=>({id:m.id,name:m.original_name,alt:m.alt_text,url:m.public_url,kind:String(m.mime_type).startsWith("video/")?"video":"image"})))).catch((e:Error)=>setMessage(e.message||"Media remote belum dapat dimuat."))},[role]);
  const upload=async(file?:File)=>{
    const label=alt.trim();
    if(!file||!label)return setMessage("Pilih file dan isi alt text sebelum upload.");
    const isVideo=file.type.startsWith("video/");
    const max=isVideo?100*1024*1024:10*1024*1024;
    if(file.size>max)return setMessage("Ukuran file maksimal "+(isVideo?"100 MB":"10 MB")+".");
    if(!["image/jpeg","image/png","image/webp","image/avif","video/mp4","video/webm"].includes(file.type))return setMessage("Format tidak didukung. Gunakan JPG, PNG, WebP, AVIF, MP4, atau WebM.");
    const pending=Boolean(apiBase&&role!=="demo"),previewUrl=URL.createObjectURL(file);
    const localItem:UploadItem={name:file.name,alt:label,url:previewUrl,kind:isVideo?"video":"image",pending};
    setItems(x=>[localItem,...x]);setAlt("");setMessage(pending?"Upload sedang berlangsung…":"Media ditambahkan ke demo lokal.");
    if(!apiBase||role==="demo")return;
    try{
      const form=new FormData();form.append("file",file);form.append("altText",label);
      const response=await fetch(apiBase+"/admin/media/upload",{method:"POST",credentials:"include",body:form});
      const raw=await response.text();let body:any=null;try{body=raw?JSON.parse(raw):null}catch{throw new Error("API upload mengembalikan response yang tidak terbaca.")};
      if(!response.ok)throw new Error(body?.error||"Upload media gagal.");
      URL.revokeObjectURL(previewUrl);setItems(x=>x.filter(item=>item.url!==previewUrl).concat({id:body.data.id,name:file.name,alt:label,url:body.data.publicUrl,kind:isVideo?"video":"image"}));setMessage("✓ Media berhasil diupload. Sekarang pilih tujuan di bawah, lalu klik Pasang ke tujuan.");
    }catch(e){URL.revokeObjectURL(previewUrl);setItems(x=>x.filter(item=>item.url!==previewUrl));setMessage(e instanceof Error?e.message:"Upload dibatalkan.")} 
  };
  const useAsset=(asset:UploadItem)=>{
    if(asset.pending)return setMessage("Tunggu upload selesai sebelum memasang media.");
    if(asset.kind!==selected.kind)return setMessage("Tujuan ini membutuhkan "+(selected.kind==="video"?"video.":"image."));
    const n=structuredClone(content);
    if(selected.id==="hero.posterImageUrl"){n.hero.posterImageUrl=asset.url;n.hero.posterAlt=asset.alt}
    else if(selected.id==="hero.videoUrl")n.hero.videoUrl=asset.url;
    else if(selected.id==="about.imageUrl"){n.about.imageUrl=asset.url;n.about.imageAlt=asset.alt;n.about.mediaType="image"}
    else if(selected.id==="about.videoUrl"){n.about.videoUrl=asset.url;n.about.mediaType="video"}
    else if(selected.id.startsWith("contact-gallery:")){const image=n.contact.galleryImages[Number(selected.id.slice(16))];if(image){image.imageUrl=asset.url;image.imageAlt=asset.alt}}
    else if(selected.id.startsWith("client:")){const client=n.clients.find(x=>x.id===selected.id.slice(7));if(client){client.logoUrl=asset.url;client.logoAlt=asset.alt;client.isPlaceholder=false}}
    else if(selected.id.startsWith("portfolio:")){const item=n.portfolio.find(x=>x.id===selected.id.slice(10));if(item){item.coverImageUrl=asset.url;item.coverImageAlt=asset.alt;item.isPlaceholder=false}}
    update(n);setApplied(asset.url);setMessage("✓ "+asset.name+" dipasang ke "+selected.label+". Klik Simpan draft untuk menyimpan perubahan.");
  };
  const remove=async(asset:UploadItem)=>{try{if(apiBase&&asset.id)await apiJson("/admin/media/"+asset.id,{method:"DELETE"});if(asset.url.startsWith("blob:"))URL.revokeObjectURL(asset.url);setItems(v=>v.filter(x=>x.url!==asset.url));setMessage("Media dihapus dari library.")}catch(e){setMessage(e instanceof Error?e.message:"Media gagal dihapus.")}};
  return <><PageHeading title="Upload & pasang media" copy="Alur sederhana untuk website-v2: upload sekali, pilih tujuan yang jelas, lalu pasang ke slot yang dipilih."/>
    <section className="media-flow">
      <div className="media-flow-step"><span className="media-step-number">1</span><div className="media-step-copy"><p className="overline">UPLOAD MEDIA</p><h2>Masukkan image atau video</h2><p>Image maksimal 10 MB. Video MP4/WebM maksimal 100 MB. Alt text wajib agar website tetap aksesibel.</p><Field label="Alt text"><input aria-label="Alt text" value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Contoh: Logo Koperasi Astra"/></Field><label className="primary-action file-action"><IconPlus/>Pilih file<input type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" onChange={e=>upload(e.target.files?.[0])}/></label></div></div>
      <div className="media-flow-step"><span className="media-step-number">2</span><div className="media-step-copy"><p className="overline">PILIH TUJUAN</p><h2>Media ini muncul di mana?</h2><p>Pilih satu slot. Status <b>Terisi</b> berarti klik Pasang akan mengganti asset di slot tersebut.</p></div><div className="media-target-groups">{targetGroups.map(group=><section className="media-target-group" key={group.label}><div className="media-target-group-heading"><strong>{group.label}</strong><small>{group.description}</small></div><div className="media-target-list">{group.items.map(item=><button type="button" className={"media-target "+(selected.id===item.id?"is-selected":"")} key={item.id} onClick={()=>setTarget(item.id)}><span className="media-target-index">{item.label.split("—")[0].trim().replace("Thumbnail ","").replace("Client ","").replace("Grid ","")}</span><span><b>{item.label}</b><small>{item.currentUrl?"Terisi · klik untuk mengganti":item.detail}</small></span>{selected.id===item.id?<IconCheck/>:<IconChevronRight/>}</button>)}</div></section>)}</div></div>
      {message&&<div className={"media-message "+(message.startsWith("✓")?"is-success":"")} role="status">{message}</div>}
    </section>
    <section className="media-library"><div className="media-library-heading"><div><p className="overline">MEDIA LIBRARY</p><h2>Pilih file yang mau dipasang</h2><p>Tujuan aktif: <b>{selected.label}</b> <span className="media-kind">({selected.kind==="image"?"image":"video"})</span></p></div><span className="media-library-count">{items.length} media</span></div><div className="media-grid">{!items.length?<div className="empty-state"><IconPhoto/><h3>Belum ada media</h3><p>Upload pertama akan tampil di sini.</p></div>:items.map(x=><article className={applied===x.url?"is-applied":""} key={x.url}>{x.kind==="video"?<video src={x.url} controls preload="metadata"/>:<img src={x.url} alt={x.alt}/>}<b>{x.name}</b><small>{x.alt}</small><div className="media-actions"><button className="secondary-action" disabled={Boolean(x.pending)} onClick={()=>useAsset(x)}>{x.pending?"Mengupload…":applied===x.url?"Terpasang":"Pasang ke tujuan"}</button><button className="secondary-action danger-action" onClick={()=>remove(x)} aria-label={"Hapus "+x.name}><IconTrash/>Hapus</button></div></article>)}</div></section>
  </> 
}function Review(){
  const [entries,setEntries]=useState<any[]>([]),[message,setMessage]=useState("");
  const [reasons,setReasons]=useState<Record<string,string>>({});
  const load=()=>{if(apiBase)apiJson("/admin/content/entries?status=pending_review").then(setEntries).catch((e:Error)=>setMessage(e.message))};useEffect(load,[]);
  const act=async(id:string,action:"approve"|"reject")=>{try{const init:RequestInit={method:"PATCH"};if(action==="reject"){const reason=(reasons[id]||"").trim();if(reason.length<3)return setMessage("Alasan penolakan minimal 3 karakter.");init.body=JSON.stringify({reason})}await apiJson(`/admin/content/entries/${id}/${action}`,init);setEntries(v=>v.filter(i=>i.id!==id));setMessage(action==="approve"?"Konten dipublish.":"Konten dikembalikan ke writer dengan catatan revisi.")}catch(e){setMessage(e instanceof Error?e.message:"Aksi gagal.")}};
  return <><PageHeading title="Review Queue" copy="Writer mengirim draft; superadmin menyetujui atau mengembalikannya dengan alasan revisi."/><section className="panel">{message&&<div className="contrast-note">{message}</div>}{!entries.length?<div className="empty-state"><IconCheck/><h3>Queue bersih</h3><p>Belum ada entry menunggu review.</p></div>:entries.map(x=><article className="review-card" key={x.id}><div className="user-row"><span className="avatar">{x.contentType.slice(0,2).toUpperCase()}</span><div><b>{x.slug}</b><small>{x.contentType}</small></div><Status value={x.status}/><button className="secondary-action" onClick={()=>act(x.id,"approve")}><IconCheck/>Approve</button></div><div className="review-reject"><Field label="Alasan revisi"><input value={reasons[x.id]||""} onChange={e=>setReasons(v=>({...v,[x.id]:e.target.value}))} placeholder="Jelaskan bagian yang perlu diperbaiki" maxLength={500}/></Field><button className="secondary-action danger-action" onClick={()=>act(x.id,"reject")}><IconX/>Reject</button></div></article>)}</section></>
}
function Users(){
  const [users,setUsers]=useState<any[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState("admin_writer"),[message,setMessage]=useState("");
  const load=()=>{if(apiBase)apiJson("/admin/users").then(setUsers).catch((e:Error)=>setMessage(e.message))};useEffect(load,[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!apiBase)return setMessage("Hubungkan API untuk membuat user.");try{const user=await apiJson("/admin/users",{method:"POST",body:JSON.stringify({email,password,role})});setUsers(v=>[{...user,status:"active"},...v]);setEmail("");setPassword("");setMessage("User berhasil dibuat.")}catch(x){setMessage(x instanceof Error?x.message:"Gagal membuat user.")}};
  const updateUser=async(id:string,patch:{role?:string;status?:string})=>{try{const user=await apiJson(`/admin/users/${id}`,{method:"PATCH",body:JSON.stringify(patch)});setUsers(v=>v.map(x=>x.id===id?{...x,...user}:x));setMessage("Akses user diperbarui.")}catch(e){setMessage(e instanceof Error?e.message:"Akses gagal diperbarui.")}};
  return <><PageHeading title="Users" copy="Khusus superadmin. Ubah role dan status akses tanpa menghapus riwayat user."/><div className="settings-grid"><section className="panel"><div className="panel-title"><p className="overline">ACCESS</p><h2>Daftar user</h2></div>{users.length?users.map(x=><div className="user-row user-manage-row" key={x.id}><span className="avatar">{x.email.slice(0,2).toUpperCase()}</span><div><b>{x.email}</b><small>{x.status||"active"}</small></div><Field label="Role"><select value={x.role} onChange={e=>updateUser(x.id,{role:e.target.value})}><option value="admin_writer">Admin writer</option><option value="superadmin">Superadmin</option></select></Field><Field label="Status"><select value={x.status||"active"} onChange={e=>updateUser(x.id,{status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></Field></div>):<div className="empty-state"><IconUsers/><h3>Belum memuat user</h3><p>Login sebagai superadmin untuk data remote.</p></div>}{message&&<div className="contrast-note">{message}</div>}</section><form className="panel card-form" onSubmit={create}><div className="panel-title"><p className="overline">NEW USER</p><h2>Tambah akses</h2></div><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Password" hint="Minimal 12 karakter."><input type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><Field label="Role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="admin_writer">Admin writer</option><option value="superadmin">Superadmin</option></select></Field><button className="primary-action" type="submit"><IconPlus/>Tambah user</button></form></div></>
}
function Preview({content}:{content:PublicSitePayload}){
  const[d,setD]=useState<"desktop"|"tablet"|"mobile">("desktop"),frame=useRef<HTMLIFrameElement>(null);
  const widths={desktop:1440,tablet:768,mobile:390};
  const publicUrl=import.meta.env.VITE_PUBLIC_SITE_URL||`${window.location.protocol}//${window.location.hostname}:4173`;
  const send=()=>frame.current?.contentWindow?.postMessage({type:"perakaria:preview",content},new URL(publicUrl).origin);
  useEffect(send,[content,d]);
  return <><PageHeading title="Responsive Preview" copy="Render website draft lengkap dari komponen public yang sama sebelum submit atau publish."><div className="device-switch"><button className={d==="desktop"?"active":""} onClick={()=>setD("desktop")}><IconDeviceDesktop/></button><button className={d==="tablet"?"active":""} onClick={()=>setD("tablet")}><IconDeviceTablet/></button><button className={d==="mobile"?"active":""} onClick={()=>setD("mobile")}><IconDeviceMobile/></button></div></PageHeading><div className="preview-stage"><div className="preview-frame" style={{width:`min(100%, ${widths[d]}px)`}}><iframe ref={frame} title="Preview website Perakaria" src={publicUrl} onLoad={send}/></div></div></>
}
type RemoteEntry = { id:string; contentType:string; slug:string; status:string };
const contentInputs=(content:PublicSitePayload)=>[
  {contentType:"site_settings",slug:"site",data:content.settings,sortOrder:0,isVisible:true},
  {contentType:"theme_settings",slug:"theme",data:content.theme,sortOrder:0,isVisible:true},
  {contentType:"hero",slug:"hero",data:content.hero,sortOrder:0,isVisible:content.hero.isVisible},
  {contentType:"about",slug:"about",data:content.about,sortOrder:0,isVisible:true},
  {contentType:"expertise",slug:"expertise",data:content.expertise,sortOrder:0,isVisible:true},
  {contentType:"contact",slug:"contact",data:content.contact,sortOrder:0,isVisible:true},
  ...content.sections.map(x=>({contentType:"section_settings",slug:x.id,data:x,sortOrder:x.order,isVisible:x.isVisible})),
  ...content.skills.map(x=>({contentType:"skill",slug:x.id,data:x,sortOrder:x.order,isVisible:x.isVisible})),
  ...content.services.map(x=>({contentType:"service",slug:x.id,data:x,sortOrder:x.order,isVisible:x.isVisible})),
  ...content.portfolio.map(x=>({contentType:"portfolio",slug:x.id,data:x,sortOrder:x.order,isVisible:x.isVisible})),
  ...content.clients.map(x=>({contentType:"client",slug:x.id,data:x,sortOrder:x.order,isVisible:x.isVisible})),
].map(x=>({...x,locale:"id" as const}));
async function apiJson(url:string,init?:RequestInit){const response=await fetch(`${apiBase}${url}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const raw=await response.text();let body:{data?:unknown;error?:string}|null=null;try{body=raw?JSON.parse(raw):null}catch{const detail=raw.trim().replace(/\s+/g," ").slice(0,160);throw new Error(`CMS API mengembalikan response non-JSON (HTTP ${response.status})${detail?`: ${detail}`:"."}`)}if(!response.ok)throw new Error(body?.error||`Permintaan CMS gagal (HTTP ${response.status}).`);return body?.data as any}
async function syncRemote(content:PublicSitePayload){const existing=await apiJson("/admin/content/entries") as RemoteEntry[];const byKey=new Map<string,RemoteEntry>();const priority=(status:string)=>["draft","rejected","pending_review","published","archived"].indexOf(status);for(const entry of existing){const key=`${entry.contentType}:${entry.slug}`,current=byKey.get(key);if(!current||priority(entry.status)<priority(current.status))byKey.set(key,entry)}const result:RemoteEntry[]=[];for(const input of contentInputs(content)){const current=byKey.get(`${input.contentType}:${input.slug}`);if(current){const updated=await apiJson(`/admin/content/entries/${current.id}`,{method:"PUT",body:JSON.stringify(input)});result.push({...current,id:updated.id,status:updated.status||current.status})}else{const created=await apiJson("/admin/content/entries",{method:"POST",body:JSON.stringify(input)});result.push({id:created.id,contentType:input.contentType,slug:input.slug,status:"draft"})}}return result}

export default function App(){
  const[auth,setAuth]=useState(false),[error,setError]=useState(""),[view,setView]=useState<View>("dashboard"),[menu,setMenu]=useState(false);
  const[role,setRole]=useState<"superadmin"|"admin_writer"|"demo">("demo"),[notice,setNotice]=useState("");
  const[content,setContent]=useState<PublicSitePayload>(readLocalDraft);
  const[dirty,setDirty]=useState(false),[saved,setSaved]=useState("");
  const update=(n:PublicSitePayload)=>{setContent(n);setDirty(true)};
  const save=async()=>{try{localStorage.setItem("perakaria-cms-draft",JSON.stringify(content));if(apiBase&&role!=="demo")await syncRemote(content);setSaved(new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}));setDirty(false);setNotice(apiBase&&role!=="demo"?"Draft tersimpan ke CMS API.":"Draft tersimpan lokal.")}catch(x){setNotice(x instanceof Error?x.message:"Gagal menyimpan draft.")}};
  const publish=async()=>{try{setNotice("Menyinkronkan konten...");const entries=await syncRemote(content);for(const entry of entries){if(role==="superadmin"){await apiJson(`/admin/content/entries/${entry.id}/publish`,{method:"PATCH"});continue}let status=entry.status;if(status==="draft"||status==="rejected"){await apiJson(`/admin/content/entries/${entry.id}/submit-review`,{method:"PATCH"});status="pending_review"}}setDirty(false);setNotice(role==="superadmin"?"Konten berhasil dipublish.":"Konten berhasil dikirim untuk review.")}catch(x){setNotice(x instanceof Error?x.message:"Workflow gagal.")}};
  const login=async(e:string,p:string,d=false)=>{if(d||!apiBase){setAuth(true);setRole("demo");setError("");return}try{const user=await apiJson("/admin/auth/login",{method:"POST",body:JSON.stringify({email:e,password:p})});setRole(user.role);const site=await apiJson("/public/site?locale=id");const content=publicSitePayloadSchema.parse(site);content.clients=content.clients.filter(client=>client.name!=="Puteri Indonesia"&&client.name!=="Enjoy Jakarta");setContent(content);setAuth(true);setError("")}catch(x){setError(x instanceof Error?x.message:"Login gagal.")}};
  const logout=async()=>{if(apiBase&&role!=="demo")try{await apiJson("/admin/auth/logout",{method:"POST"})}catch{}setAuth(false)};
  if(!auth)return <Login onLogin={login} error={error}/>;
  return <div className="admin-shell"><aside className={menu?"is-open":""}><div className="sidebar-brand"><div className="admin-wordmark">PERAKA<span>RIA</span></div><small>CONTENT SYSTEM / V2</small></div><nav>{nav.map(([v,l,I])=><button className={view===v?"active":""} key={v} onClick={()=>{setView(v);setMenu(false)}}><I/><span>{l}</span></button>)}</nav><button className="logout" onClick={logout}><IconLogout/>Keluar</button></aside><div className="admin-main"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setMenu(!menu)}>{menu?<IconX/>:<IconMenu2/>}</button><div><p>Workspace / <b>{nav.find(x=>x[0]===view)?.[1]}</b></p>{notice?<small>{notice}</small>:saved&&<small>Tersimpan {saved}</small>}</div><div className="top-actions"><button className="secondary-action" onClick={()=>setView("preview")}><IconEye/>Preview</button>{apiBase&&role!=="demo"&&<button className="secondary-action" onClick={publish}><IconSend/>{role==="superadmin"?"Publish":"Submit"}</button>}<button className="primary-action" disabled={!dirty} onClick={save}><IconCheck/>Simpan draft</button></div></header><main className="admin-content">{view==="dashboard"&&<Dashboard go={setView}/>} {view==="sections"&&<Sections content={content} update={update}/>} {view==="expertise"&&<ExpertiseEditor content={content} update={update}/>} {(view==="services"||view==="portfolio"||view==="clients")&&<Collection kind={view} content={content} update={update}/>} {view==="media"&&<Media content={content} update={update} role={role}/>} {view==="theme"&&<Theme content={content} update={update}/>} {view==="review"&&<Review/>} {view==="users"&&<Users/>} {view==="preview"&&<Preview content={content}/>}</main></div></div>
}














