// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it } from "vitest";
import App from "./App";
beforeEach(()=>{localStorage.clear();Object.defineProperty(URL,"createObjectURL",{value:()=>"blob:perakaria-test",configurable:true});Object.defineProperty(URL,"revokeObjectURL",{value:()=>undefined,configurable:true})});
afterEach(cleanup);
describe("Perakaria CMS demo",()=>{
  it("edits and saves hero draft locally",()=>{render(<App/>);fireEvent.click(screen.getByRole("button",{name:/buka demo lokal/i}));fireEvent.click(screen.getAllByRole("button",{name:/home sections/i})[0]);const headline=screen.getAllByLabelText("Headline")[0];fireEvent.change(headline,{target:{value:"Headline dari CMS"}});const save=screen.getByRole("button",{name:/simpan draft/i});expect(save.hasAttribute("disabled")).toBe(false);fireEvent.click(save);expect(localStorage.getItem("perakaria-cms-draft")).toContain("Headline dari CMS")});
  it("edits expertise copy and skill details from CMS",()=>{render(<App/>);fireEvent.click(screen.getByRole("button",{name:/buka demo lokal/i}));fireEvent.click(screen.getAllByRole("button",{name:/about & expertise/i})[0]);fireEvent.change(screen.getByLabelText("Headline"),{target:{value:"Expertise dari CMS"}});fireEvent.change(screen.getAllByLabelText("Nama skill")[0],{target:{value:"Virtual Production"}});fireEvent.click(screen.getByRole("button",{name:/simpan draft/i}));const draft=localStorage.getItem("perakaria-cms-draft")||"";expect(draft).toContain("Expertise dari CMS");expect(draft).toContain("Virtual Production")});
  it("assigns and removes a media asset without copying URLs",()=>{render(<App/>);fireEvent.click(screen.getByRole("button",{name:/buka demo lokal/i}));fireEvent.click(screen.getAllByRole("button",{name:/media library/i})[0]);fireEvent.change(screen.getByLabelText("Alt text"),{target:{value:"Still frame produksi"}});const input=document.querySelector("input[type=file]") as HTMLInputElement;fireEvent.change(input,{target:{files:[new File([new Uint8Array([1])],"still.png",{type:"image/png"})]}});fireEvent.change(screen.getByLabelText("Terapkan asset ke"),{target:{value:"client:client-1"}});fireEvent.click(screen.getByRole("button",{name:"Gunakan"}));fireEvent.click(screen.getByRole("button",{name:/simpan draft/i}));expect(localStorage.getItem("perakaria-cms-draft")).toContain("blob:perakaria-test");expect(localStorage.getItem("perakaria-cms-draft")).toContain("Still frame produksi");expect(screen.getByRole("option",{name:/Foto skill: Video Production/i})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/hapus still.png/i}));expect(screen.queryByAltText("Still frame produksi")).toBeNull()});
  it("switches to the complete responsive preview",()=>{render(<App/>);fireEvent.click(screen.getByRole("button",{name:/buka demo lokal/i}));fireEvent.click(screen.getAllByRole("button",{name:/responsive preview/i})[0]);expect(screen.getByTitle("Preview website Perakaria")).toBeTruthy()});
});